### ISSUE TITLE
Provide ground on J10

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/bela-hardware#2]
Two pads on J10 are currently nc but could conveniently be connected to ground.

**Comment by apmcpherson** [comment]
I left those NC because on J9, they are connected to the minus output of the left and right line outputs (which are otherwise unused on the current design). If someone cuts the traces to install an effect loop, I at least didn't want there to be any harm in connecting all four pads across. If having ground there is useful, perhaps it would be better to add another pad so it is unambiguous.
